SUCCESS = (0, 'Success %s')
INVALID_REQUEST = (1, 'Only AJAX Request is allowed %s')
INTEGRITY_ERROR = (2, 'Duplicate Entry %s')
MISSING_PARAMS_ERROR = (3, 'Post Parameters Error %s')
NOT_EXIST = (4, 'No Such Entry %s')
ENTRY_IN_USING = (5, 'The entry is in use now %s')
JSON_FORMAT_ERROR = (6, 'JSON format is not valid %s')
REQUEST_URL_ERROR = (7, 'Request URL is not valid %s')